In [1]:
import datetime
import pandas as pd
df = pd.read_csv('~\Downloads\Hot Stuff.csv')
df['WeekID'] = [datetime.datetime.strptime(df['WeekID'][x], '%m/%d/%Y') for x in range(len(df['WeekID']))]
df.head()

,url,WeekID,Week Position,Song,Performer,SongID,Instance,Previous Week Position,Peak Position,Weeks on Chart
0,http://www.billboard.com/charts/hot-100/1958-0...,1958-08-02,1,Poor Little Fool,Ricky Nelson,Poor Little FoolRicky Nelson,1,NaN,1,1
1,http://www.billboard.com/charts/hot-100/1995-1...,1995-12-02,1,One Sweet Day,Mariah Carey & Boyz II Men,One Sweet DayMariah Carey & Boyz II Men,1,NaN,1,1
2,http://www.billboard.com/charts/hot-100/1997-1...,1997-10-11,1,Candle In The Wind 1997/Something About The Wa...,Elton John,Candle In The Wind 1997/Something About The Wa...,1,NaN,1,1
3,http://www.billboard.com/charts/hot-100/2006-0...,2006-07-01,1,Do I Make You Proud,Taylor Hicks,Do I Make You ProudTaylor Hicks,1,NaN,1,1
4,http://www.billboard.com/charts/hot-100/2009-1...,2009-10-24,1,3,Britney Spears,3Britney Spears,1,NaN,1,1

In [2]:
date = pd.Timestamp(datetime.date(2010,1,9))
df = df[df['WeekID'] >= date]
df.head()

,url,WeekID,Week Position,Song,Performer,SongID,Instance,Previous Week Position,Peak Position,Weeks on Chart
5,http://www.billboard.com/charts/hot-100/2011-0...,2011-02-26,1,Born This Way,Lady Gaga,Born This WayLady Gaga,1,NaN,1,1
6,http://www.billboard.com/charts/hot-100/2012-0...,2012-03-03,1,Part Of Me,Katy Perry,Part Of MeKaty Perry,1,NaN,1,1
7,http://www.billboard.com/charts/hot-100/2014-0...,2014-09-06,1,Shake It Off,Taylor Swift,Shake It OffTaylor Swift,1,NaN,1,1
8,http://www.billboard.com/charts/hot-100/2016-0...,2016-02-20,1,Pillowtalk,Zayn,PillowtalkZayn,1,NaN,1,1
9,http://www.billboard.com/charts/hot-100/2016-0...,2016-05-28,1,Can't Stop The Feeling!,Justin Timberlake,Can't Stop The Feeling!Justin Timberlake,1,NaN,1,1

In [3]:
df = df[df['Week Position'] <= 10]
df = df.reset_index(drop=True)
df.head()

,url,WeekID,Week Position,Song,Performer,SongID,Instance,Previous Week Position,Peak Position,Weeks on Chart
0,http://www.billboard.com/charts/hot-100/2011-0...,2011-02-26,1,Born This Way,Lady Gaga,Born This WayLady Gaga,1,NaN,1,1
1,http://www.billboard.com/charts/hot-100/2012-0...,2012-03-03,1,Part Of Me,Katy Perry,Part Of MeKaty Perry,1,NaN,1,1
2,http://www.billboard.com/charts/hot-100/2014-0...,2014-09-06,1,Shake It Off,Taylor Swift,Shake It OffTaylor Swift,1,NaN,1,1
3,http://www.billboard.com/charts/hot-100/2016-0...,2016-02-20,1,Pillowtalk,Zayn,PillowtalkZayn,1,NaN,1,1
4,http://www.billboard.com/charts/hot-100/2016-0...,2016-05-28,1,Can't Stop The Feeling!,Justin Timberlake,Can't Stop The Feeling!Justin Timberlake,1,NaN,1,1

In [4]:
df = df.drop(columns=['url', 'SongID', 'Instance', 'Previous Week Position', 'Weeks on Chart'])

In [5]:
cols = list(df.columns)
cols

['WeekID', 'Week Position', 'Song', 'Performer', 'Peak Position']

In [6]:
df2 = pd.DataFrame([[pd.Timestamp(datetime.date(2018,1,3)), 1, 'Perfect', 'Ed Sheeran', 1], [pd.Timestamp(datetime.date(2018,1,3)), 2, 'Rockstar', 'Post Malone Featuring 21 Savage', 1], [pd.Timestamp(datetime.date(2018,1,3)), 3, 'Havana', 'Camila Cabello Featuring Young Thug', 2], [pd.Timestamp(datetime.date(2018,1,3)), 4, 'Gucci Gang', 'Lil Pump', 3], [pd.Timestamp(datetime.date(2018,1,3)), 5, 'No Limit', 'G-Eazy Featuring A$AP Rocky & Cardi B', 5], [pd.Timestamp(datetime.date(2018,1,3)), 6, 'Thunder', 'Imagine Dragons', 4], [pd.Timestamp(datetime.date(2018,1,3)), 7, 'MotorSport', 'Migos, Nicki Minaj & Cardi B', 6], [pd.Timestamp(datetime.date(2018,1,3)), 8, 'Too Good At Goodbyes', 'Sam Smith', 4], [pd.Timestamp(datetime.date(2018,1,3)), 9, 'All I Want For Christmas Is You', 'Mariah Carey', 9], [pd.Timestamp(datetime.date(2018,1,3)), 10, 'Bad At Love', 'Halsey', 8], [pd.Timestamp(datetime.date(2020,1,4)), 1, 'All I Want For Christmas Is You', 'Mariah Carey', 1], [pd.Timestamp(datetime.date(2020,1,4)), 2, "Rockin' Around The Christmas Tree", 'Brenda Lee', 2], [pd.Timestamp(datetime.date(2020,1,4)), 3, 'Jingle Bell Rock', 'Bobby Helms', 3], [pd.Timestamp(datetime.date(2020,1,4)), 4, 'A Holly Jolly Christmas', 'Burl Ives', 4], [pd.Timestamp(datetime.date(2020,1,4)), 5, 'Circles', 'Post Malone', 1], [pd.Timestamp(datetime.date(2020,1,4)), 6, 'Roxanne', 'Arizona Zervas', 4], [pd.Timestamp(datetime.date(2020,1,4)), 7, "It's The Most Wonderful Time Of The Year", 'Andy Williams', 7], [pd.Timestamp(datetime.date(2020,1,4)), 8, 'Someone You Loved', 'Lewis Capaldi', 1], [pd.Timestamp(datetime.date(2020,1,4)), 9, 'Memories', 'Maroon 5', 4], [pd.Timestamp(datetime.date(2020,1,4)), 10, 'Good As Hell', 'Lizzo', 3]], columns=cols)
df2

,WeekID,Week Position,Song,Performer,Peak Position
0,2018-01-03,1,Perfect,Ed Sheeran,1
1,2018-01-03,2,Rockstar,Post Malone Featuring 21 Savage,1
2,2018-01-03,3,Havana,Camila Cabello Featuring Young Thug,2
3,2018-01-03,4,Gucci Gang,Lil Pump,3
4,2018-01-03,5,No Limit,G-Eazy Featuring A$AP Rocky & Cardi B,5
5,2018-01-03,6,Thunder,Imagine Dragons,4
6,2018-01-03,7,MotorSport,"Migos, Nicki Minaj & Cardi B",6
7,2018-01-03,8,Too Good At Goodbyes,Sam Smith,4
8,2018-01-03,9,All I Want For Christmas Is You,Mariah Carey,9
9,2018-01-03,10,Bad At Love,Halsey,8
10,2020-01-04,1,All I Want For Christmas Is You,Mariah Carey,1
11,2020-01-04,2,Rockin' Around The Christmas Tree,Brenda Lee,2
12,2020-01-04,3,Jingle Bell Rock,Bobby Helms,3
13,2020-01-04,4,A Holly Jolly Christmas,Burl Ives,4
14,2020-01-04,5,Circles,Post Malone,1
15,2020-01-04,6,Roxanne,Arizona Zervas,4
16,2020-01-04,7,It's The Most Wonderful Time Of The Year,Andy Williams,7
17,2020-01-04,8,Someone You Loved,Lewis Capaldi,1
18,2020-01-04,9,Memories,Maroon 5,4
19,2020-01-04,10,Good As Hell,Lizzo,3

In [7]:
df = df.append(df2, ignore_index=True)
df

,WeekID,Week Position,Song,Performer,Peak Position
0,2011-02-26,1,Born This Way,Lady Gaga,1
1,2012-03-03,1,Part Of Me,Katy Perry,1
2,2014-09-06,1,Shake It Off,Taylor Swift,1
3,2016-02-20,1,Pillowtalk,Zayn,1
4,2016-05-28,1,Can't Stop The Feeling!,Justin Timberlake,1
...,...,...,...,...,...
5225,2020-01-04,6,Roxanne,Arizona Zervas,4
5226,2020-01-04,7,It's The Most Wonderful Time Of The Year,Andy Williams,7
5227,2020-01-04,8,Someone You Loved,Lewis Capaldi,1
5228,2020-01-04,9,Memories,Maroon 5,4
5229,2020-01-04,10,Good As Hell,Lizzo,3

In [8]:
df = df.sort_values(["WeekID", "Week Position"], ascending = (True, True))
df = df.reset_index(drop=True)
df

,WeekID,Week Position,Song,Performer,Peak Position
0,2010-01-09,1,TiK ToK,Ke$ha,1
1,2010-01-09,2,Replay,Iyaz,2
2,2010-01-09,3,Bad Romance,Lady Gaga,2
3,2010-01-09,4,Fireflies,Owl City,1
4,2010-01-09,5,Empire State Of Mind,Jay-Z + Alicia Keys,1
...,...,...,...,...,...
5225,2020-01-04,6,Roxanne,Arizona Zervas,4
5226,2020-01-04,7,It's The Most Wonderful Time Of The Year,Andy Williams,7
5227,2020-01-04,8,Someone You Loved,Lewis Capaldi,1
5228,2020-01-04,9,Memories,Maroon 5,4
5229,2020-01-04,10,Good As Hell,Lizzo,3

In [9]:
df[df['Song'] == 'S&M']

,WeekID,Week Position,Song,Performer,Peak Position
597,2011-02-26,8,S&M,Rihanna Featuring Britney Spears,8
606,2011-03-05,7,S&M,Rihanna Featuring Britney Spears,7
614,2011-03-12,5,S&M,Rihanna Featuring Britney Spears,5
622,2011-03-19,3,S&M,Rihanna Featuring Britney Spears,3
633,2011-03-26,4,S&M,Rihanna Featuring Britney Spears,3
642,2011-04-02,3,S&M,Rihanna Featuring Britney Spears,3
651,2011-04-09,2,S&M,Rihanna Featuring Britney Spears,2
661,2011-04-16,2,S&M,Rihanna Featuring Britney Spears,2
671,2011-04-23,2,S&M,Rihanna Featuring Britney Spears,2
680,2011-04-30,1,S&M,Rihanna Featuring Britney Spears,1
693,2011-05-07,4,S&M,Rihanna Featuring Britney Spears,1
705,2011-05-14,6,S&M,Rihanna Featuring Britney Spears,1
718,2011-05-21,9,S&M,Rihanna Featuring Britney Spears,1

In [10]:
df.loc[(df.Song == 'S&M'),'Performer']='Rihanna'
df[df['Song'] == 'S&M']

        WeekID  Week Position Song Performer  Peak Position
597 2011-02-26              8  S&M   Rihanna              8
606 2011-03-05              7  S&M   Rihanna              7
614 2011-03-12              5  S&M   Rihanna              5
622 2011-03-19              3  S&M   Rihanna              3
633 2011-03-26              4  S&M   Rihanna              3
642 2011-04-02              3  S&M   Rihanna              3
651 2011-04-09              2  S&M   Rihanna              2
661 2011-04-16              2  S&M   Rihanna              2
671 2011-04-23              2  S&M   Rihanna              2
680 2011-04-30              1  S&M   Rihanna              1
693 2011-05-07              4  S&M   Rihanna              1
705 2011-05-14              6  S&M   Rihanna              1
718 2011-05-21              9  S&M   Rihanna              1

In [11]:
df.loc[(df['WeekID'] == pd.Timestamp(datetime.date(2011,4,30))) & (df['Song'] == 'S&M'), 'Performer'] = "Rihanna Featuring Britney Spears"
df[df['Song'] == 'S&M']

,WeekID,Week Position,Song,Performer,Peak Position
597,2011-02-26,8,S&M,Rihanna,8
606,2011-03-05,7,S&M,Rihanna,7
614,2011-03-12,5,S&M,Rihanna,5
622,2011-03-19,3,S&M,Rihanna,3
633,2011-03-26,4,S&M,Rihanna,3
642,2011-04-02,3,S&M,Rihanna,3
651,2011-04-09,2,S&M,Rihanna,2
661,2011-04-16,2,S&M,Rihanna,2
671,2011-04-23,2,S&M,Rihanna,2
680,2011-04-30,1,S&M,Rihanna Featuring Britney Spears,1
693,2011-05-07,4,S&M,Rihanna,1
705,2011-05-14,6,S&M,Rihanna,1
718,2011-05-21,9,S&M,Rihanna,1

In [12]:
df[df['Song'] == 'Till The World Ends']

,WeekID,Week Position,Song,Performer,Peak Position
638,2011-03-26,9,Till The World Ends,Britney Spears Featuring Nicki Minaj & Ke$ha,9
677,2011-04-23,8,Till The World Ends,Britney Spears Featuring Nicki Minaj & Ke$ha,8
688,2011-04-30,9,Till The World Ends,Britney Spears Featuring Nicki Minaj & Ke$ha,8
702,2011-05-14,3,Till The World Ends,Britney Spears Featuring Nicki Minaj & Ke$ha,3
715,2011-05-21,6,Till The World Ends,Britney Spears Featuring Nicki Minaj & Ke$ha,3
727,2011-05-28,8,Till The World Ends,Britney Spears Featuring Nicki Minaj & Ke$ha,3
736,2011-06-04,7,Till The World Ends,Britney Spears Featuring Nicki Minaj & Ke$ha,3
746,2011-06-11,7,Till The World Ends,Britney Spears Featuring Nicki Minaj & Ke$ha,3
758,2011-06-18,9,Till The World Ends,Britney Spears Featuring Nicki Minaj & Ke$ha,3

In [13]:
df.loc[(df.Song == 'Till The World Ends'),'Performer']='Britney Spears'
df.loc[(df['WeekID'] == pd.Timestamp(datetime.date(2011,5,14))) & (df['Song'] == 'Till The World Ends'), 'Performer'] = "Britney Spears Featuring Nicki Minaj & Ke$ha"
df[df['Song'] == 'Till The World Ends']

,WeekID,Week Position,Song,Performer,Peak Position
638,2011-03-26,9,Till The World Ends,Britney Spears,9
677,2011-04-23,8,Till The World Ends,Britney Spears,8
688,2011-04-30,9,Till The World Ends,Britney Spears,8
702,2011-05-14,3,Till The World Ends,Britney Spears Featuring Nicki Minaj & Ke$ha,3
715,2011-05-21,6,Till The World Ends,Britney Spears,3
727,2011-05-28,8,Till The World Ends,Britney Spears,3
736,2011-06-04,7,Till The World Ends,Britney Spears,3
746,2011-06-11,7,Till The World Ends,Britney Spears,3
758,2011-06-18,9,Till The World Ends,Britney Spears,3

In [14]:
df[df['Song'] == 'Dirt Road Anthem']

        WeekID  Week Position              Song     Performer  Peak Position
768 2011-06-25              9  Dirt Road Anthem  Jason Aldean              9
776 2011-07-02              7  Dirt Road Anthem  Jason Aldean              7

In [15]:
df.loc[(df['WeekID'] == pd.Timestamp(datetime.date(2011,7,2))) & (df['Song'] == 'Dirt Road Anthem'), 'Performer'] = "Jason Aldean Featuring Ludacris"
df[df['Song'] == 'Dirt Road Anthem']

,WeekID,Week Position,Song,Performer,Peak Position
768,2011-06-25,9,Dirt Road Anthem,Jason Aldean,9
776,2011-07-02,7,Dirt Road Anthem,Jason Aldean Featuring Ludacris,7

In [16]:
df[(df['Song'] == 'Perfect') & (df['Performer'] == 'Ed Sheeran')]

         WeekID  Week Position     Song   Performer  Peak Position
4099 2017-11-11             10  Perfect  Ed Sheeran             10
4117 2017-11-25              8  Perfect  Ed Sheeran              8
4126 2017-12-02              7  Perfect  Ed Sheeran              7
4134 2017-12-09              5  Perfect  Ed Sheeran              5
4142 2017-12-16              3  Perfect  Ed Sheeran              3
4150 2017-12-23              1  Perfect  Ed Sheeran              1
4160 2017-12-30              1  Perfect  Ed Sheeran              1
4170 2018-01-03              1  Perfect  Ed Sheeran              1
4180 2018-01-06              1  Perfect  Ed Sheeran              1
4190 2018-01-13              1  Perfect  Ed Sheeran              1
4200 2018-01-20              1  Perfect  Ed Sheeran              1
4211 2018-01-27              2  Perfect  Ed Sheeran              1
4221 2018-02-03              2  Perfect  Ed Sheeran              1
4231 2018-02-10              2  Perfect  Ed Sheeran              1
4241 2018-02-17              2  Perfect  Ed Sheeran              1
4251 2018-02-24              2  Perfect  Ed Sheeran              1
4261 2018-03-03              2  Perfect  Ed Sheeran              1
4272 2018-03-10              3  Perfect  Ed Sheeran              1
4281 2018-03-17              2  Perfect  Ed Sheeran              1
4291 2018-03-24              2  Perfect  Ed Sheeran              1
4302 2018-03-31              3  Perfect  Ed Sheeran              1
4314 2018-04-07              5  Perfect  Ed Sheeran              1
4326 2018-04-14              7  Perfect  Ed Sheeran              1
4336 2018-04-21              7  Perfect  Ed Sheeran              1
4346 2018-04-28              7  Perfect  Ed Sheeran              1
4378 2018-05-19              9  Perfect  Ed Sheeran              1
4389 2018-05-26             10  Perfect  Ed Sheeran              1

In [17]:
df.loc[(df['WeekID'] >= pd.Timestamp(datetime.date(2017,12,23))) & (df['WeekID'] <= pd.Timestamp(datetime.date(2018,1,13))) & (df['Song'] == 'Perfect'), 'Performer'] = "Ed Sheeran and Beyonce"

In [18]:
df[(df['Song'] == 'Perfect') & (df['Performer'].str.contains('Ed Sheeran'))]

         WeekID  Week Position     Song               Performer  Peak Position
4099 2017-11-11             10  Perfect              Ed Sheeran             10
4117 2017-11-25              8  Perfect              Ed Sheeran              8
4126 2017-12-02              7  Perfect              Ed Sheeran              7
4134 2017-12-09              5  Perfect              Ed Sheeran              5
4142 2017-12-16              3  Perfect              Ed Sheeran              3
4150 2017-12-23              1  Perfect  Ed Sheeran and Beyonce              1
4160 2017-12-30              1  Perfect  Ed Sheeran and Beyonce              1
4170 2018-01-03              1  Perfect  Ed Sheeran and Beyonce              1
4180 2018-01-06              1  Perfect  Ed Sheeran and Beyonce              1
4190 2018-01-13              1  Perfect  Ed Sheeran and Beyonce              1
4200 2018-01-20              1  Perfect              Ed Sheeran              1
4211 2018-01-27              2  Perfect              Ed Sheeran              1
4221 2018-02-03              2  Perfect              Ed Sheeran              1
4231 2018-02-10              2  Perfect              Ed Sheeran              1
4241 2018-02-17              2  Perfect              Ed Sheeran              1
4251 2018-02-24              2  Perfect              Ed Sheeran              1
4261 2018-03-03              2  Perfect              Ed Sheeran              1
4272 2018-03-10              3  Perfect              Ed Sheeran              1
4281 2018-03-17              2  Perfect              Ed Sheeran              1
4291 2018-03-24              2  Perfect              Ed Sheeran              1
4302 2018-03-31              3  Perfect              Ed Sheeran              1
4314 2018-04-07              5  Perfect              Ed Sheeran              1
4326 2018-04-14              7  Perfect              Ed Sheeran              1
4336 2018-04-21              7  Perfect              Ed Sheeran              1
4346 2018-04-28              7  Perfect              Ed Sheeran              1
4378 2018-05-19              9  Perfect              Ed Sheeran              1
4389 2018-05-26             10  Perfect              Ed Sheeran              1

In [19]:
df[df['Song'] == 'Old Town Road']

,WeekID,Week Position,Song,Performer,Peak Position
4840,2019-04-13,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4850,2019-04-20,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4860,2019-04-27,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4870,2019-05-04,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4880,2019-05-11,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4890,2019-05-18,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4900,2019-05-25,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4910,2019-06-01,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4920,2019-06-08,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4930,2019-06-15,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4940,2019-06-22,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4950,2019-06-29,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4960,2019-07-06,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4970,2019-07-13,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4980,2019-07-20,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4990,2019-07-27,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
5000,2019-08-03,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
5010,2019-08-10,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
5020,2019-08-17,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
5032,2019-08-24,3,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
5043,2019-08-31,4,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
5054,2019-09-07,5,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
5064,2019-09-14,5,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
5089,2019-09-28,10,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
5099,2019-10-05,10,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
5109,2019-10-12,10,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1

In [20]:
df.loc[(df['WeekID'] == pd.Timestamp(datetime.date(2019,4,13))) & (df['Song'] == 'Old Town Road'), 'Performer'] = "Lil Nas X"
df[df['Song'] == 'Old Town Road']

,WeekID,Week Position,Song,Performer,Peak Position
4840,2019-04-13,1,Old Town Road,Lil Nas X,1
4850,2019-04-20,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4860,2019-04-27,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4870,2019-05-04,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4880,2019-05-11,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4890,2019-05-18,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4900,2019-05-25,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4910,2019-06-01,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4920,2019-06-08,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4930,2019-06-15,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4940,2019-06-22,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4950,2019-06-29,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4960,2019-07-06,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4970,2019-07-13,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4980,2019-07-20,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
4990,2019-07-27,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
5000,2019-08-03,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
5010,2019-08-10,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
5020,2019-08-17,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
5032,2019-08-24,3,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
5043,2019-08-31,4,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
5054,2019-09-07,5,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
5064,2019-09-14,5,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
5089,2019-09-28,10,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
5099,2019-10-05,10,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1
5109,2019-10-12,10,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1

In [21]:
df[df['Performer'].str.contains("Ke$ha", regex=False)]

,WeekID,Week Position,Song,Performer,Peak Position
0,2010-01-09,1,TiK ToK,Ke$ha,1
10,2010-01-16,1,TiK ToK,Ke$ha,1
20,2010-01-23,1,TiK ToK,Ke$ha,1
26,2010-01-23,7,Blah Blah Blah,Ke$ha Featuring 3OH!3,7
30,2010-01-30,1,TiK ToK,Ke$ha,1
...,...,...,...,...,...
2155,2014-02-22,6,Timber,Pitbull Featuring Ke$ha,1
2166,2014-03-01,7,Timber,Pitbull Featuring Ke$ha,1
2179,2014-03-08,10,Timber,Pitbull Featuring Ke$ha,1
2189,2014-03-15,10,Timber,Pitbull Featuring Ke$ha,1
2199,2014-03-22,10,Timber,Pitbull Featuring Ke$ha,1

In [22]:
df['Performer'].unique()

array(['Ke$ha', 'Iyaz', 'Lady Gaga', 'Owl City', 'Jay-Z + Alicia Keys',
       'Jason Derulo', 'Jay Sean Featuring Lil Wayne', 'Miley Cyrus',
       'David Guetta Featuring Akon',
       'Jay Sean Featuring Sean Paul & Lil Jon', 'The Black Eyed Peas',
       'Ke$ha Featuring 3OH!3', 'Young Money Featuring Lloyd',
       'Rihanna Featuring Jeezy', 'Train', 'Ludacris', 'Taylor Swift',
       'Justin Bieber Featuring Ludacris', 'Lady Antebellum',
       'Artists For Haiti', 'Trey Songz Featuring Fabolous', 'Rihanna',
       'Taio Cruz Featuring Ludacris', 'B.o.B Featuring Bruno Mars',
       'Lady Gaga Featuring Beyonce', 'Usher Featuring will.i.am',
       'Adam Lambert', 'B.o.B Featuring Hayley Williams',
       'Jay-Z + Mr. Hudson', 'Eminem', '3OH!3 Featuring Ke$ha',
       'Katy Perry Featuring Snoop Dogg', 'La Roux',
       'Travie McCoy Featuring Bruno Mars', 'Drake', 'Mike Posner',
       'Eminem Featuring Rihanna', 'Taio Cruz',
       'Enrique Iglesias Featuring Pitbull', 'Katy Perry',
       'Usher Featuring Pitbull', 'Lil Wayne Featuring Drake',
       'Bruno Mars', 'B.o.B Featuring Rivers Cuomo', 'Nelly',
       'Flo Rida Featuring David Guetta',
       'Far*East Movement Featuring Cataracs & Dev',
       'Trey Songz Featuring Nicki Minaj', 'P!nk',
       'Rihanna Featuring Drake', 'Glee Cast', 'Cee Lo Green',
       'Lil Wayne Featuring Cory Gunz', 'Wiz Khalifa',
       'Enrique Iglesias Featuring Ludacris & DJ Frank E',
       'Britney Spears', 'Pitbull Featuring T-Pain',
       'Far*East Movement Featuring Ryan Tedder',
       'Dr. Dre Featuring Eminem & Skylar Grey',
       'Justin Bieber Featuring Jaden Smith',
       'Katy Perry Featuring Kanye West',
       'Jennifer Lopez Featuring Pitbull',
       'Chris Brown Featuring Lil Wayne & Busta Rhymes',
       'Jeremih Featuring 50 Cent', 'Adele',
       'Rihanna Featuring Britney Spears',
       'Britney Spears Featuring Nicki Minaj & Ke$ha',
       'Pitbull Featuring Ne-Yo, Afrojack & Nayer',
       'LMFAO Featuring Lauren Bennett & GoonRock', 'Lupe Fiasco',
       'DJ Khaled Featuring Drake, Rick Ross & Lil Wayne', 'Jason Aldean',
       'Nicki Minaj', 'Jason Aldean Featuring Ludacris',
       'Maroon 5 Featuring Christina Aguilera', 'Lil Wayne',
       'OneRepublic', 'Hot Chelle Rae', 'Demi Lovato',
       'Bad Meets Evil Featuring Bruno Mars', 'Foster The People',
       'Gym Class Heroes Featuring Adam Levine',
       'Cobra Starship Featuring Sabi', 'LMFAO',
       'B.o.B Featuring Lil Wayne', 'David Guetta Featuring Usher',
       'Rihanna Featuring Calvin Harris',
       'Snoop Dogg & Wiz Khalifa Featuring Bruno Mars',
       'Drake Featuring Nicki Minaj', 'Kelly Clarkson', 'Flo Rida',
       'Drake Featuring Rihanna', 'Jay Z Kanye West',
       'T-Pain Featuring Wiz Khalifa & Lily Allen',
       'Big Sean Featuring Nicki Minaj', 'Jason Mraz', 'Tyga',
       'David Guetta Featuring Nicki Minaj', 'Jessie J',
       'fun. Featuring Janelle Monae', 'Whitney Houston',
       'Madonna Featuring Nicki Minaj & M.I.A.', 'Chris Brown',
       'The Wanted', 'Gotye Featuring Kimbra', 'Flo Rida Featuring Sia',
       'Justin Bieber', 'One Direction', 'Carly Rae Jepsen',
       'Maroon 5 Featuring Wiz Khalifa', 'Phillip Phillips',
       'Ellie Goulding', 'Usher', 'David Guetta Featuring Sia', 'fun.',
       'Justin Bieber Featuring Big Sean', 'Maroon 5',
       'Owl City & Carly Rae Jepsen', 'Neon Trees', 'Alex Clare', 'PSY',
       'Ne-Yo', 'The Lumineers', 'Justin Bieber Featuring Nicki Minaj',
       'Macklemore & Ryan Lewis Featuring Wanz',
       'will.i.am & Britney Spears',
       'Swedish House Mafia Featuring John Martin',
       'Justin Timberlake Featuring JAY Z',
       'A$AP Rocky Featuring Drake, 2 Chainz & Kendrick Lamar',
       'Calvin Harris Featuring Florence Welch', 'Baauer',
       'Rihanna Featuring Mikky Ekko',
       'Lil Wayne Featuring Drake & Future', 'P!nk Featuring Nate Ruess',
       'Pitbull Featuring Christina Aguilera', 'Imagine Dragons',
       'Ariana Grande Featuring Mac Miller',
       'Macklemore & Ryan Lewis Featuring Ray Dalton',
       'Florida Georgia Line Featuring Nelly', 'Justin Timberlake',
       'Icona Pop Featuring Charli XCX', 'Selena Gomez',
       'Daft Punk Featuring Pharrell Williams',
       'Robin Thicke Featuring T.I. + Pharrell', 'Anna Kendrick',
       'Jay Z Featuring Justin Timberlake', 'Zedd Featuring Foxes',
       'Capital Cities', 'Avicii', 'Lana Del Rey & Cedric Gervais',
       'Lorde', 'Drake Featuring Majid Jordan', 'Ylvis',
       'Pitbull Featuring Ke$ha', 'Passenger',
       'A Great Big World & Christina Aguilera',
       'Katy Perry Featuring Juicy J', 'Bastille',
       'Jason Derulo Featuring 2 Chainz', 'Beyonce Featuring Jay Z',
       'Pharrell Williams', 'John Legend', 'Idina Menzel', 'Soko',
       'Aloe Blacc', 'DJ Snake & Lil Jon',
       'Chris Brown Featuring Lil Wayne & French Montana Or Too $hort Or Tyga',
       'Iggy Azalea Featuring Charli XCX',
       'Ariana Grande Featuring Iggy Azalea', 'Paramore',
       'Michael Jackson & Justin Timberlake', 'Coldplay', 'Nico & Vinz',
       'Jason Derulo Featuring Snoop Dogg', 'MAGIC!', 'Calvin Harris',
       'Sam Smith', 'Disclosure Featuring Sam Smith', 'Sia',
       'Jessie J, Ariana Grande & Nicki Minaj', 'Meghan Trainor',
       'Charli XCX', 'Ariana Grande Featuring Zedd',
       'Iggy Azalea Featuring Rita Ora', 'Jeremih Featuring YG',
       'Tove Lo', 'Clean Bandit Featuring Jess Glynne', 'Bobby Shmurda',
       'Ed Sheeran', 'Hozier', 'Ariana Grande & The Weeknd', 'Nick Jonas',
       'Mark Ronson Featuring Bruno Mars', 'Fall Out Boy',
       'Rihanna & Kanye West & Paul McCartney', 'The Weeknd',
       'Pitbull & Ne-Yo', 'Fetty Wap',
       'Flo Rida Featuring Sage The Gemini & Lookas',
       'Natalie La Rose Featuring Jeremih',
       'Wiz Khalifa Featuring Charlie Puth', 'WALK THE MOON', 'T-Wayne',
       'Taylor Swift Featuring Kendrick Lamar',
       'David Guetta Featuring Nicki Minaj, Bebe Rexha & Afrojack',
       'Andy Grammer', 'OMI', 'Silento',
       'Selena Gomez Featuring A$AP Rocky',
       'Skrillex & Diplo With Justin Bieber', 'Rachel Platten',
       'Major Lazer & DJ Snake Featuring MO', 'Fetty Wap Featuring Monty',
       'Fetty Wap Featuring Remy Boyz', 'R. City Featuring Adam Levine',
       'Shawn Mendes', 'Ariana Grande',
       'Meghan Trainor Featuring John Legend', 'Elle King',
       'Alessia Cara', 'twenty one pilots',
       'The Chainsmokers Featuring Rozes', 'Zayn', 'G-Eazy x Bebe Rexha',
       'DNCE', 'Lukas Graham', 'Fifth Harmony Featuring Ty Dolla $ign',
       'Desiigner', 'Drake Featuring WizKid & Kyla',
       'Prince And The Revolution', 'Prince', 'Beyonce',
       'The Chainsmokers Featuring Daya',
       'Calvin Harris Featuring Rihanna', 'Sia Featuring Sean Paul',
       'Kent Jones', 'Major Lazer Featuring Justin Bieber & MO',
       'The Chainsmokers Featuring Halsey',
       'Charlie Puth Featuring Selena Gomez',
       'DJ Snake Featuring Justin Bieber',
       'D.R.A.M. Featuring Lil Yachty', 'The Weeknd Featuring Daft Punk',
       "gnash Featuring Olivia O'Brien",
       'Ariana Grande Featuring Nicki Minaj',
       'Maroon 5 Featuring Kendrick Lamar',
       'Zay Hilfigerrr & Zayion McCall',
       'Rae Sremmurd Featuring Gucci Mane',
       'Machine Gun Kelly x Camila Cabello', 'Zayn / Taylor Swift',
       'J. Cole', 'Migos Featuring Lil Uzi Vert', 'The Chainsmokers',
       'Big Sean', 'Katy Perry Featuring Skip Marley',
       'The Chainsmokers & Coldplay', 'Kodak Black',
       'Clean Bandit Featuring Sean Paul & Anne-Marie',
       'KYLE Featuring Lil Yachty',
       'Drake Featuring Quavo & Travis Scott', 'Kendrick Lamar',
       'Sam Hunt', 'Harry Styles', 'Future', 'Lil Uzi Vert',
       'Zedd & Alessia Cara',
       'Luis Fonsi & Daddy Yankee Featuring Justin Bieber',
       'Kygo x Selena Gomez',
       'DJ Khaled Featuring Justin Bieber, Quavo, Chance The Rapper & Lil Wayne',
       'Post Malone Featuring Quavo',
       'DJ Khaled Featuring Rihanna & Bryson Tiller',
       'French Montana Featuring Swae Lee', 'Charlie Puth', 'Cardi B',
       'Yo Gotti Featuring Nicki Minaj',
       'Logic Featuring Alessia Cara & Khalid',
       'Liam Payne Featuring Quavo', 'Post Malone Featuring 21 Savage',
       'Portugal. The Man', 'J Balvin & Willy William Featuring Beyonce',
       'Camila Cabello Featuring Young Thug', 'Lil Pump',
       'Maroon 5 Featuring SZA', 'G-Eazy Featuring A$AP Rocky & Cardi B',
       'Ed Sheeran and Beyonce', 'Halsey', 'Migos, Nicki Minaj & Cardi B',
       'Mariah Carey', 'Bruno Mars & Cardi B', 'Dua Lipa',
       'Justin Timberlake Featuring Chris Stapleton',
       'The Weeknd & Kendrick Lamar', 'Migos',
       'Bebe Rexha & Florida Georgia Line', 'BlocBoy JB Featuring Drake',
       'Kendrick Lamar & SZA', 'Post Malone Featuring Ty Dolla $ign',
       'Zedd, Maren Morris & Grey', 'XXXTENTACION',
       'Lil Dicky Featuring Chris Brown', 'Migos Featuring Drake',
       'Cardi B, Bad Bunny & J Balvin', 'Camila Cabello', 'Post Malone',
       'Childish Gambino', 'Lil Baby & Drake', 'Ella Mai', 'BTS',
       'Maroon 5 Featuring Cardi B', 'Kanye West', 'Juice WRLD',
       'Drake Featuring Michael Jackson',
       '6ix9ine Featuring Nicki Minaj & Murda Beatz',
       'Tyga Featuring Offset',
       'DJ Khaled Featuring Justin Bieber, Chance The Rapper & Quavo',
       'Travis Scott', 'Khalid & Normani',
       'Eminem Featuring Joyner Lucas', 'Kanye West & Lil Pump',
       '5 Seconds Of Summer', 'Lil Wayne Featuring Kendrick Lamar',
       'Lil Wayne Featuring XXXTENTACION',
       'Lil Wayne Featuring Travis Scott', 'Lil Baby & Gunna',
       'Lady Gaga & Bradley Cooper', 'Marshmello & Bastille',
       'Kodak Black Featuring Travis Scott & Offset',
       'Bad Bunny Featuring Drake', 'Post Malone & Swae Lee', 'Sheck Wes',
       'Panic! At The Disco', 'Meek Mill Featuring Drake',
       'Andy Williams', 'Bobby Helms', 'Brenda Lee', 'Burl Ives',
       'benny blanco, Halsey & Khalid', 'Cardi B & Bruno Mars',
       'Blueface', 'Jonas Brothers', 'Lil Nas X', 'Billie Eilish',
       'Lil Nas X Featuring Billy Ray Cyrus', 'Khalid',
       'Sam Smith & Normani', 'BTS Featuring Halsey',
       'Taylor Swift Featuring Brendon Urie', 'Logic Featuring Eminem',
       'Ed Sheeran & Justin Bieber', 'Ava Max', 'DaBaby',
       'Chris Brown Featuring Drake', 'Drake Featuring Rick Ross',
       'Shawn Mendes & Camila Cabello', 'Lizzo',
       'Post Malone Featuring Young Thug', 'Lil Tecca',
       'Ariana Grande & Social House',
       'Post Malone Featuring Ozzy Osbourne & Travis Scott',
       'Lewis Capaldi', 'Dan + Shay & Justin Bieber',
       'Juice WRLD & YoungBoy Never Broke Again', 'Arizona Zervas',
       'Tones And I'], dtype=object)

In [23]:
df['Performer'] = df['Performer'].astype(object)

In [24]:
ind = df.loc[(df['Performer'] == "Juice WRLD & YoungBoy Never Broke Again"),'Performer'].index.values.tolist()
s = pd.Series((["Juice WRLD", "YoungBoy Never Broke Again"] for i in range(len(ind))), index = ind)
df.loc[(df['Performer'] == "Juice WRLD & YoungBoy Never Broke Again"),'Performer'] = s

In [25]:
ind = df.loc[(df['Song'] == "Money In The Grave"),'Performer'].index.values.tolist()
s = pd.Series((['Drake', 'Rick Ross'] for i in range(len(ind))), index = ind)
df.loc[(df['Song'] == "Money In The Grave"),'Performer'] = s

In [26]:
for i in range(len(df)):
    if isinstance(df['Performer'][i], list) == True:
        continue
    else:
        df['Performer'][i] = [df['Performer'][i]]
df

C:\Users\HELoz\Anaconda\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

,WeekID,Week Position,Song,Performer,Peak Position
0,2010-01-09,1,TiK ToK,[Ke$ha],1
1,2010-01-09,2,Replay,[Iyaz],2
2,2010-01-09,3,Bad Romance,[Lady Gaga],2
3,2010-01-09,4,Fireflies,[Owl City],1
4,2010-01-09,5,Empire State Of Mind,[Jay-Z + Alicia Keys],1
...,...,...,...,...,...
5225,2020-01-04,6,Roxanne,[Arizona Zervas],4
5226,2020-01-04,7,It's The Most Wonderful Time Of The Year,[Andy Williams],7
5227,2020-01-04,8,Someone You Loved,[Lewis Capaldi],1
5228,2020-01-04,9,Memories,[Maroon 5],4
5229,2020-01-04,10,Good As Hell,[Lizzo],3

In [27]:
artists = []
for i in range(len(df)):
    for j in range(len(df['Performer'][i])):
        if df['Performer'][i][j] in artists:
            continue
        else:
            artists.append(df['Performer'][i][j])
artists

['Ke$ha',
 'Iyaz',
 'Lady Gaga',
 'Owl City',
 'Jay-Z + Alicia Keys',
 'Jason Derulo',
 'Jay Sean Featuring Lil Wayne',
 'Miley Cyrus',
 'David Guetta Featuring Akon',
 'Jay Sean Featuring Sean Paul & Lil Jon',
 'The Black Eyed Peas',
 'Ke$ha Featuring 3OH!3',
 'Young Money Featuring Lloyd',
 'Rihanna Featuring Jeezy',
 'Train',
 'Ludacris',
 'Taylor Swift',
 'Justin Bieber Featuring Ludacris',
 'Lady Antebellum',
 'Artists For Haiti',
 'Trey Songz Featuring Fabolous',
 'Rihanna',
 'Taio Cruz Featuring Ludacris',
 'B.o.B Featuring Bruno Mars',
 'Lady Gaga Featuring Beyonce',
 'Usher Featuring will.i.am',
 'Adam Lambert',
 'B.o.B Featuring Hayley Williams',
 'Jay-Z + Mr. Hudson',
 'Eminem',
 '3OH!3 Featuring Ke$ha',
 'Katy Perry Featuring Snoop Dogg',
 'La Roux',
 'Travie McCoy Featuring Bruno Mars',
 'Drake',
 'Mike Posner',
 'Eminem Featuring Rihanna',
 'Taio Cruz',
 'Enrique Iglesias Featuring Pitbull',
 'Katy Perry',
 'Usher Featuring Pitbull',
 'Lil Wayne Featuring Drake',
 'Bruno Mars',
 'B.o.B Featuring Rivers Cuomo',
 'Nelly',
 'Flo Rida Featuring David Guetta',
 'Far*East Movement Featuring Cataracs & Dev',
 'Trey Songz Featuring Nicki Minaj',
 'P!nk',
 'Rihanna Featuring Drake',
 'Glee Cast',
 'Cee Lo Green',
 'Lil Wayne Featuring Cory Gunz',
 'Wiz Khalifa',
 'Enrique Iglesias Featuring Ludacris & DJ Frank E',
 'Britney Spears',
 'Pitbull Featuring T-Pain',
 'Far*East Movement Featuring Ryan Tedder',
 'Dr. Dre Featuring Eminem & Skylar Grey',
 'Justin Bieber Featuring Jaden Smith',
 'Katy Perry Featuring Kanye West',
 'Jennifer Lopez Featuring Pitbull',
 'Chris Brown Featuring Lil Wayne & Busta Rhymes',
 'Jeremih Featuring 50 Cent',
 'Adele',
 'Rihanna Featuring Britney Spears',
 'Britney Spears Featuring Nicki Minaj & Ke$ha',
 'Pitbull Featuring Ne-Yo, Afrojack & Nayer',
 'LMFAO Featuring Lauren Bennett & GoonRock',
 'Lupe Fiasco',
 'DJ Khaled Featuring Drake, Rick Ross & Lil Wayne',
 'Jason Aldean',
 'Nicki Minaj',
 'Jason Aldean Featuring Ludacris',
 'Maroon 5 Featuring Christina Aguilera',
 'Lil Wayne',
 'OneRepublic',
 'Hot Chelle Rae',
 'Demi Lovato',
 'Bad Meets Evil Featuring Bruno Mars',
 'Foster The People',
 'Gym Class Heroes Featuring Adam Levine',
 'Cobra Starship Featuring Sabi',
 'LMFAO',
 'B.o.B Featuring Lil Wayne',
 'David Guetta Featuring Usher',
 'Rihanna Featuring Calvin Harris',
 'Snoop Dogg & Wiz Khalifa Featuring Bruno Mars',
 'Drake Featuring Nicki Minaj',
 'Kelly Clarkson',
 'Flo Rida',
 'Drake Featuring Rihanna',
 'Jay Z Kanye West',
 'T-Pain Featuring Wiz Khalifa & Lily Allen',
 'Big Sean Featuring Nicki Minaj',
 'Jason Mraz',
 'Tyga',
 'David Guetta Featuring Nicki Minaj',
 'Jessie J',
 'fun. Featuring Janelle Monae',
 'Whitney Houston',
 'Madonna Featuring Nicki Minaj & M.I.A.',
 'Chris Brown',
 'The Wanted',
 'Gotye Featuring Kimbra',
 'Flo Rida Featuring Sia',
 'Justin Bieber',
 'One Direction',
 'Carly Rae Jepsen',
 'Maroon 5 Featuring Wiz Khalifa',
 'Phillip Phillips',
 'Ellie Goulding',
 'Usher',
 'David Guetta Featuring Sia',
 'fun.',
 'Justin Bieber Featuring Big Sean',
 'Maroon 5',
 'Owl City & Carly Rae Jepsen',
 'Neon Trees',
 'Alex Clare',
 'PSY',
 'Ne-Yo',
 'The Lumineers',
 'Justin Bieber Featuring Nicki Minaj',
 'Macklemore & Ryan Lewis Featuring Wanz',
 'will.i.am & Britney Spears',
 'Swedish House Mafia Featuring John Martin',
 'Justin Timberlake Featuring JAY Z',
 'A$AP Rocky Featuring Drake, 2 Chainz & Kendrick Lamar',
 'Calvin Harris Featuring Florence Welch',
 'Baauer',
 'Rihanna Featuring Mikky Ekko',
 'Lil Wayne Featuring Drake & Future',
 'P!nk Featuring Nate Ruess',
 'Pitbull Featuring Christina Aguilera',
 'Imagine Dragons',
 'Ariana Grande Featuring Mac Miller',
 'Macklemore & Ryan Lewis Featuring Ray Dalton',
 'Florida Georgia Line Featuring Nelly',
 'Justin Timberlake',
 'Icona Pop Featuring Charli XCX',
 'Selena Gomez',
 'Daft Punk Featuring Pharrell Williams',
 'Robin Thicke Featuring T.I. + Pharrell',
 'Anna Kendrick',
 'Jay Z Featuring Justin Timberlake',
 'Zedd Featuring Foxes',
 'Capital Cities',
 'Avicii',
 'Lana Del Rey & Cedric Gervais',
 'Lorde',
 'Drake Featuring Majid Jordan',
 'Ylvis',
 'Pitbull Featuring Ke$ha',
 'Passenger',
 'A Great Big World & Christina Aguilera',
 'Katy Perry Featuring Juicy J',
 'Bastille',
 'Jason Derulo Featuring 2 Chainz',
 'Beyonce Featuring Jay Z',
 'Pharrell Williams',
 'John Legend',
 'Idina Menzel',
 'Soko',
 'Aloe Blacc',
 'DJ Snake & Lil Jon',
 'Chris Brown Featuring Lil Wayne & French Montana Or Too $hort Or Tyga',
 'Iggy Azalea Featuring Charli XCX',
 'Ariana Grande Featuring Iggy Azalea',
 'Paramore',
 'Michael Jackson & Justin Timberlake',
 'Coldplay',
 'Nico & Vinz',
 'Jason Derulo Featuring Snoop Dogg',
 'MAGIC!',
 'Calvin Harris',
 'Sam Smith',
 'Disclosure Featuring Sam Smith',
 'Sia',
 'Jessie J, Ariana Grande & Nicki Minaj',
 'Meghan Trainor',
 'Charli XCX',
 'Ariana Grande Featuring Zedd',
 'Iggy Azalea Featuring Rita Ora',
 'Jeremih Featuring YG',
 'Tove Lo',
 'Clean Bandit Featuring Jess Glynne',
 'Bobby Shmurda',
 'Ed Sheeran',
 'Hozier',
 'Ariana Grande & The Weeknd',
 'Nick Jonas',
 'Mark Ronson Featuring Bruno Mars',
 'Fall Out Boy',
 'Rihanna & Kanye West & Paul McCartney',
 'The Weeknd',
 'Pitbull & Ne-Yo',
 'Fetty Wap',
 'Flo Rida Featuring Sage The Gemini & Lookas',
 'Natalie La Rose Featuring Jeremih',
 'Wiz Khalifa Featuring Charlie Puth',
 'WALK THE MOON',
 'T-Wayne',
 'Taylor Swift Featuring Kendrick Lamar',
 'David Guetta Featuring Nicki Minaj, Bebe Rexha & Afrojack',
 'Andy Grammer',
 'OMI',
 'Silento',
 'Selena Gomez Featuring A$AP Rocky',
 'Skrillex & Diplo With Justin Bieber',
 'Rachel Platten',
 'Major Lazer & DJ Snake Featuring MO',
 'Fetty Wap Featuring Monty',
 'Fetty Wap Featuring Remy Boyz',
 'R. City Featuring Adam Levine',
 'Shawn Mendes',
 'Ariana Grande',
 'Meghan Trainor Featuring John Legend',
 'Elle King',
 'Alessia Cara',
 'twenty one pilots',
 'The Chainsmokers Featuring Rozes',
 'Zayn',
 'G-Eazy x Bebe Rexha',
 'DNCE',
 'Lukas Graham',
 'Fifth Harmony Featuring Ty Dolla $ign',
 'Desiigner',
 'Drake Featuring WizKid & Kyla',
 'Prince And The Revolution',
 'Prince',
 'Beyonce',
 'The Chainsmokers Featuring Daya',
 'Calvin Harris Featuring Rihanna',
 'Sia Featuring Sean Paul',
 'Kent Jones',
 'Major Lazer Featuring Justin Bieber & MO',
 'The Chainsmokers Featuring Halsey',
 'Charlie Puth Featuring Selena Gomez',
 'DJ Snake Featuring Justin Bieber',
 'D.R.A.M. Featuring Lil Yachty',
 'The Weeknd Featuring Daft Punk',
 "gnash Featuring Olivia O'Brien",
 'Ariana Grande Featuring Nicki Minaj',
 'Maroon 5 Featuring Kendrick Lamar',
 'Zay Hilfigerrr & Zayion McCall',
 'Rae Sremmurd Featuring Gucci Mane',
 'Machine Gun Kelly x Camila Cabello',
 'Zayn / Taylor Swift',
 'J. Cole',
 'Migos Featuring Lil Uzi Vert',
 'The Chainsmokers',
 'Big Sean',
 'Katy Perry Featuring Skip Marley',
 'The Chainsmokers & Coldplay',
 'Kodak Black',
 'Clean Bandit Featuring Sean Paul & Anne-Marie',
 'KYLE Featuring Lil Yachty',
 'Drake Featuring Quavo & Travis Scott',
 'Kendrick Lamar',
 'Sam Hunt',
 'Harry Styles',
 'Future',
 'Lil Uzi Vert',
 'Zedd & Alessia Cara',
 'Luis Fonsi & Daddy Yankee Featuring Justin Bieber',
 'Kygo x Selena Gomez',
 'DJ Khaled Featuring Justin Bieber, Quavo, Chance The Rapper & Lil Wayne',
 'Post Malone Featuring Quavo',
 'DJ Khaled Featuring Rihanna & Bryson Tiller',
 'French Montana Featuring Swae Lee',
 'Charlie Puth',
 'Cardi B',
 'Yo Gotti Featuring Nicki Minaj',
 'Logic Featuring Alessia Cara & Khalid',
 'Liam Payne Featuring Quavo',
 'Post Malone Featuring 21 Savage',
 'Portugal. The Man',
 'J Balvin & Willy William Featuring Beyonce',
 'Camila Cabello Featuring Young Thug',
 'Lil Pump',
 'Maroon 5 Featuring SZA',
 'G-Eazy Featuring A$AP Rocky & Cardi B',
 'Ed Sheeran and Beyonce',
 'Halsey',
 'Migos, Nicki Minaj & Cardi B',
 'Mariah Carey',
 'Bruno Mars & Cardi B',
 'Dua Lipa',
 'Justin Timberlake Featuring Chris Stapleton',
 'The Weeknd & Kendrick Lamar',
 'Migos',
 'Bebe Rexha & Florida Georgia Line',
 'BlocBoy JB Featuring Drake',
 'Kendrick Lamar & SZA',
 'Post Malone Featuring Ty Dolla $ign',
 'Zedd, Maren Morris & Grey',
 'XXXTENTACION',
 'Lil Dicky Featuring Chris Brown',
 'Migos Featuring Drake',
 'Cardi B, Bad Bunny & J Balvin',
 'Camila Cabello',
 'Post Malone',
 'Childish Gambino',
 'Lil Baby & Drake',
 'Ella Mai',
 'BTS',
 'Maroon 5 Featuring Cardi B',
 'Kanye West',
 'Juice WRLD',
 'Drake Featuring Michael Jackson',
 '6ix9ine Featuring Nicki Minaj & Murda Beatz',
 'Tyga Featuring Offset',
 'DJ Khaled Featuring Justin Bieber, Chance The Rapper & Quavo',
 'Travis Scott',
 'Khalid & Normani',
 'Eminem Featuring Joyner Lucas',
 'Kanye West & Lil Pump',
 '5 Seconds Of Summer',
 'Lil Wayne Featuring Kendrick Lamar',
 'Lil Wayne Featuring XXXTENTACION',
 'Lil Wayne Featuring Travis Scott',
 'Lil Baby & Gunna',
 'Lady Gaga & Bradley Cooper',
 'Marshmello & Bastille',
 'Kodak Black Featuring Travis Scott & Offset',
 'Bad Bunny Featuring Drake',
 'Post Malone & Swae Lee',
 'Sheck Wes',
 'Panic! At The Disco',
 'Meek Mill Featuring Drake',
 'Andy Williams',
 'Bobby Helms',
 'Brenda Lee',
 'Burl Ives',
 'benny blanco, Halsey & Khalid',
 'Cardi B & Bruno Mars',
 'Blueface',
 'Jonas Brothers',
 'Lil Nas X',
 'Billie Eilish',
 'Lil Nas X Featuring Billy Ray Cyrus',
 'Khalid',
 'Sam Smith & Normani',
 'BTS Featuring Halsey',
 'Taylor Swift Featuring Brendon Urie',
 'Logic Featuring Eminem',
 'Ed Sheeran & Justin Bieber',
 'Ava Max',
 'DaBaby',
 'Chris Brown Featuring Drake',
 'Rick Ross',
 'Shawn Mendes & Camila Cabello',
 'Lizzo',
 'Post Malone Featuring Young Thug',
 'Lil Tecca',
 'Ariana Grande & Social House',
 'Post Malone Featuring Ozzy Osbourne & Travis Scott',
 'Lewis Capaldi',
 'Dan + Shay & Justin Bieber',
 'YoungBoy Never Broke Again',
 'Arizona Zervas',
 'Tones And I']

In [28]:
len(artists)

363

In [29]:
df2 = pd.DataFrame({'Date': df['WeekID'].unique()})
df2.head()

        Date
0 2010-01-09
1 2010-01-16
2 2010-01-23
3 2010-01-30
4 2010-02-06

In [30]:
df2 = df2.set_index('Date')
df2.head()

Empty DataFrame
Columns: []
Index: [2010-01-09 00:00:00, 2010-01-16 00:00:00, 2010-01-23 00:00:00, 2010-01-30 00:00:00, 2010-02-06 00:00:00]

In [31]:
df.to_csv('C:/Users/HELoz/Downloads/2010stop10hitsdata.csv')

In [32]:
for artist in artists:
    bools = []
    for i in range(len(df)):
        if artist in df['Performer'][i]:
            bools.append(True)
        else:
            bools.append(False)
    df['In'] = bools
    a = df[df['In'] == True]
    a = a.drop_duplicates(subset=['Song']).groupby('WeekID')['In'].sum()
    df2[artist] = a
df2

SystemError: <built-in function is_scalar> returned a result with an error set

In [ ]:
df2 = df2.fillna(0)
df2 = df2.cumsum()
df2 = df2.replace(True, 1)
df2 = df2.astype(int)
df2

In [ ]:
df2 = df2.T
df2

In [ ]:
#df2.to_csv('C:/Users/HELoz/Downloads/2010stop10hitsbynumber.csv')

In [ ]:
df3 = pd.read_csv('C:/Users/HELoz/Downloads/2010stop10hitsbynumber.csv')
df3.head()

In [ ]:
import numpy as np
data = np.array(['https://media.npr.org/assets/music/news/2010/01/kesha-0845b11c071fb200859a805157bfaef03fe95b55-s800-c85.jpg', 'https://www.aceshowbiz.com/images/new_artist/iyaz.jpg', 'https://consequenceofsound.net/wp-content/uploads/2010/09/2010_09sept_ladygagatourdates.png?w=396', 'https://wordpress.wbur.org/wp-content/uploads/2013/07/APJAYZ1000.jpg', 'https://media1.popsugar-assets.com/files/thumbor/IOMPfkuHXJCbk7cy-G4ay726Jn8/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2012/02/08/1/498/4981324/3a0b4293c438f00a_96750386/i/2010-Alicia-Keys.jpg', 'https://www1.pictures.zimbio.com/gi/2014+Logie+Awards+Arrivals+1wL7ztbbxRJx.jpg', 'https://media.npr.org/assets/music/news/2010/03/jaysean-552ca431cfbcea898e5219a5d43bec3f174225ce-s800-c85.jpg', 'https://img.timeinc.net/time/photoessays/2011/summer_music/lil_wayne.jpg', 'https://akns-images.eonline.com/eol_images/Entire_Site/201998/rs_600x600-191008121945-600-miley-cyrus-pasties.jpg?fit=around|1200:1200&crop=1200:1200;center,top&output-quality=90', 'https://www.800lifestyle.com/sites/default/files/field/image/David-Guetta_2012.jpg', 'https://www1.pictures.zimbio.com/fp/Akon+2010+MTV+Video+Music+Awards+Arrivals+9V384fMOfi4l.jpg', 'https://s.abcnews.com/images/Sports/WireAP_aafc4e98c94c458aa436821ef1ecdd23_16x9_992.jpg', 'https://www.bbc.co.uk/staticarchive/801ed6fcf08cc9b7c36d347d25102be06686bea3.jpg', 'https://img.discogs.com/x8KAltREXvzs63qiwgEozOfE1zw=/fit-in/300x300/filters:strip_icc():format(jpeg):mode_rgb():quality(40)/discogs-images/A-1167089-1278446380.jpeg.jpg', 'https://i.ytimg.com/vi/QlXdbz8GYT4/hqdefault.jpg', 'https://i.pinimg.com/474x/12/28/c8/1228c8215528e4cf40d6f63553757fc1--lloyd-polite-famous-men.jpg', 'https://pmchollywoodlife.files.wordpress.com/2010/09/092110_rihanna_5441.jpg?w=544', 'https://www.dmfashionbook.com/wp-content/uploads/2010/11/youngjeezy1.jpg', 'https://www.villagevoice.com/wp-content/uploads/2010/12/trainmyspace.jpg', 'https://www.famemagazine.co.uk/wp-content/uploads/2010/01/Ludacris1.jpg', 'https://api.time.com/wp-content/uploads/2015/02/taylor-swift1.jpg?w=600&quality=85', 'https://www.telegraph.co.uk/content/dam/music/2016/02/22/justin-bieber-8-hr_trans_NvBQzQNjv4BqNJjoeBT78QIaYdkJdEY4CnGTJFJS74MYhNY6w3GNbO8.jpg', 'https://media.lehighvalleylive.com/today_impact/photo/lady-antebellum-a7dc461dad55d27d.jpg', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7b/We_Are_the_World_25_for_Haiti.png/220px-We_Are_the_World_25_for_Haiti.png', 'https://lh3.googleusercontent.com/proxy/gNqblWlxv9nLtl1znE-380fC4rlqo0Do0duZI784z76xkgoN9TdIlPYW-zd-pQp2Dmwz1j2pKJgPl-nGiOjmj6ynUqwq1P_LUm4GCbiJB_TxHPHbbtJkfEPmo5hNIJplHqQtnbO5TldiXyY68Y4vLTFCrJ8X2a_Ghkb24TvCqk94p3PE9ef1pPv70w', 'https://www4.pictures.zimbio.com/gi/B+o+B+rapper+BET+Hip+Hop+Awards+2010+Arrivals+3dXhQgdNT8-l.jpg', 'https://ca-times.brightspotcdn.com/dims4/default/7259a24/2147483647/strip/true/crop/396x512+0+0/resize/840x1086!/quality/90/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2F7c%2Fdb%2Fc89008351b23396debab286242a2%2Fsdut-bruno-mars-arrives-at-the-pre-20160901', 'https://www2.pictures.zimbio.com/gi/Usher+2010+Keep+Child+Alive+Black+Ball+Gjqt5R-ZypOl.jpg', 'https://www.rap-up.com/app/uploads/2010/06/eminem-recovery-promo-1280x720.jpg', 'https://m.media-amazon.com/images/M/MV5BYzAyNGJmNTQtN2Y5ZS00MGE4LWEzNDYtM2RhYzM1Y2FhM2MxXkEyXkFqcGdeQXVyNzI2NTQ5MTU@._V1_SY1000_CR0,0,853,1000_AL_.jpg', 'https://thesource.com/wp-content/uploads/2018/02/drake.jpg', 'https://i.pinimg.com/originals/47/5d/b7/475db7bbb112f15679183508c38a448c.jpg', 'https://www1.pictures.zimbio.com/gi/Flo+Rida+2012+NCLR+ALMA+Awards+Show+osSWMxkj0iPl.jpg', 'https://media1.popsugar-assets.com/files/thumbor/DM9qOlm598Ppb3oxORm9Ax74-7o/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2013/08/22/703/n/1922153/104f870eed7181d6_151408073_10/i/Nicki-Minaj-2012.jpg', 'https://assets.capitalfm.com/2011/35/2011-mtv-vmas-arrivals---britney-spears-1314598300-view-0.jpg', 'https://static.billboard.com/files/stylus/1366469-adele-qa-year-in-music-2011-617-409-compressed.jpg', 'https://cdn1.thr.com/sites/default/files/imagecache/landscape_928x523/2011/11/lamfao-publicity-2011-l.jpg', 'https://img.washingtonpost.com/rf/image_480w/2010-2019/WashingtonPost/2012/06/15/Style/Images/Photo_Maroon5_300RGB.jpg?uuid=_vqeiLb0EeGrVwBtAoUQ4g', 'https://i.pinimg.com/originals/34/5c/3c/345c3cb6e679b4fb6d0c17a1d4abc590.jpg', 'https://pbs.twimg.com/media/CGmKtfbUAAE04_1.jpg', 'https://2911.us/wp-content/uploads/2019/02/PostMalone_600pix.jpg', 'https://static.billboard.com/files/media/Cardi-B-press-photo-by-Raven-Varona-2018-billboard-1548-768x433.jpg']) 
ser = pd.Series(data, index =['Ke$ha', 'Iyaz', 'Lady Gaga', 'Jay-Z', 'Alicia Keys', 'Jason Derulo', 'Jay Sean', 'Lil Wayne', 'Miley Cyrus', 'David Guetta', 'Akon', 'Lil Jon', 'The Black Eyed Peas', '3OH!3', 'Young Money', 'Lloyd', 'Rihanna', 'Jeezy', 'Train', 'Ludacris', 'Taylor Swift', 'Justin Bieber', 'Lady Antebellum', 'Artists For Haiti', 'Taio Cruz', 'B.o.B', 'Bruno Mars', 'Usher', 'Eminem', 'Katy Perry', 'Drake', 'Pitbull', 'Flo Rida', 'Nicki Minaj', 'Britney Spears', 'Adele', 'LMFAO', 'Maroon 5', 'Ariana Grande', 'The Weeknd', 'Post Malone', 'Cardi B'])
ser

In [ ]:
df3 = df3.set_index('Unnamed: 0')
df3.insert(0, 'images', ser)
df3.head()

In [ ]:
#df3.to_csv('C:/Users/HELoz/Downloads/2010stop10hitsbynumbermodified.csv')

In [ ]:
#pf = pd.DataFrame([[21, 'Amol', 72, 67], [23, 'Lini', 78, 69], [32, 'Kiku', 74, 56], [52, 'Ajit', 54, 76]], columns=['rollno', 'name', 'physics', 'botony'])
pf

In [ ]:
#pf = pf.set_index('rollno')

In [ ]:
#pf = pf.T

In [ ]:
#pf.to_csv('C:/Users/HELoz/Downloads/practice.csv')

In [ ]:
df2 = pd.DataFrame({'Date': df['WeekID'].unique()})
df2

In [ ]:
bools = []
for i in range(len(df)):
    if "Ke$ha" in df['Performer'][i]:
        bools.append(True)
    else:
        bools.append(False)

In [ ]:
import numpy as np

df['In'] = bools
a = df[df['In'] == True].groupby('WeekID')['In'].sum()

In [ ]:
df2 = df2.set_index('Date')
df2

In [ ]:
df2['Ke$ha'] = a
df2 = df2.drop(['Ke$ha'], axis=1)
df2

In [ ]:
for artist in artists:
    bools = []
    for i in range(len(df)):
        if artist in df['Performer'][i]:
            bools.append(True)
        else:
            bools.append(False)
    df['In'] = bools
    a = df[df['In'] == True].groupby('WeekID')['In'].sum()
    df2[artist] = a
df2

In [ ]:
df2 = df2.fillna(0)
df2

In [ ]:
df2 = df2.cumsum()
df2

In [ ]:
df2 = df2.replace(True, 1)

In [ ]:
df2 = df2.astype(int)

In [ ]:
df2

In [ ]:
df2 = df2.T
df2

In [ ]:
#df2.to_csv('C:/Users/HELoz/Downloads/2010stop10hits.csv')

In [ ]:
import pandas as pd

df3 = pd.read_csv('C:/Users/HELoz/Downloads/2010stop10hits.csv')
df3

In [ ]:
df3 = df3.set_index('Unnamed: 0')
df3

In [ ]:
import numpy as np
data = np.array(['https://media.npr.org/assets/music/news/2010/01/kesha-0845b11c071fb200859a805157bfaef03fe95b55-s800-c85.jpg', 'https://www.aceshowbiz.com/images/new_artist/iyaz.jpg', 'https://consequenceofsound.net/wp-content/uploads/2010/09/2010_09sept_ladygagatourdates.png?w=396', 'https://vignette.wikia.nocookie.net/demi-lovato/images/3/31/Owl-city.jpg/revision/latest?cb=20140429074018', 'https://wordpress.wbur.org/wp-content/uploads/2013/07/APJAYZ1000.jpg', 'https://media1.popsugar-assets.com/files/thumbor/IOMPfkuHXJCbk7cy-G4ay726Jn8/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2012/02/08/1/498/4981324/3a0b4293c438f00a_96750386/i/2010-Alicia-Keys.jpg', 'https://www1.pictures.zimbio.com/gi/2014+Logie+Awards+Arrivals+1wL7ztbbxRJx.jpg', 'https://media.npr.org/assets/music/news/2010/03/jaysean-552ca431cfbcea898e5219a5d43bec3f174225ce-s800-c85.jpg', 'https://img.timeinc.net/time/photoessays/2011/summer_music/lil_wayne.jpg', 'https://www.800lifestyle.com/sites/default/files/field/image/David-Guetta_2012.jpg', 'https://www1.pictures.zimbio.com/fp/Akon+2010+MTV+Video+Music+Awards+Arrivals+9V384fMOfi4l.jpg', 'https://s.abcnews.com/images/Sports/WireAP_aafc4e98c94c458aa436821ef1ecdd23_16x9_992.jpg', 'https://www.bbc.co.uk/staticarchive/801ed6fcf08cc9b7c36d347d25102be06686bea3.jpg', 'https://i.ytimg.com/vi/QlXdbz8GYT4/hqdefault.jpg', 'https://i.pinimg.com/474x/12/28/c8/1228c8215528e4cf40d6f63553757fc1--lloyd-polite-famous-men.jpg', 'https://pmchollywoodlife.files.wordpress.com/2010/09/092110_rihanna_5441.jpg?w=544', 'https://www.dmfashionbook.com/wp-content/uploads/2010/11/youngjeezy1.jpg', 'https://www.villagevoice.com/wp-content/uploads/2010/12/trainmyspace.jpg', 'https://www.famemagazine.co.uk/wp-content/uploads/2010/01/Ludacris1.jpg', 'https://api.time.com/wp-content/uploads/2015/02/taylor-swift1.jpg?w=600&quality=85', 'https://www.telegraph.co.uk/content/dam/music/2016/02/22/justin-bieber-8-hr_trans_NvBQzQNjv4BqNJjoeBT78QIaYdkJdEY4CnGTJFJS74MYhNY6w3GNbO8.jpg', 'https://media.lehighvalleylive.com/today_impact/photo/lady-antebellum-a7dc461dad55d27d.jpg', 'https://lh3.googleusercontent.com/proxy/gNqblWlxv9nLtl1znE-380fC4rlqo0Do0duZI784z76xkgoN9TdIlPYW-zd-pQp2Dmwz1j2pKJgPl-nGiOjmj6ynUqwq1P_LUm4GCbiJB_TxHPHbbtJkfEPmo5hNIJplHqQtnbO5TldiXyY68Y4vLTFCrJ8X2a_Ghkb24TvCqk94p3PE9ef1pPv70w', 'https://www4.pictures.zimbio.com/gi/B+o+B+rapper+BET+Hip+Hop+Awards+2010+Arrivals+3dXhQgdNT8-l.jpg', 'https://ca-times.brightspotcdn.com/dims4/default/7259a24/2147483647/strip/true/crop/396x512+0+0/resize/840x1086!/quality/90/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2F7c%2Fdb%2Fc89008351b23396debab286242a2%2Fsdut-bruno-mars-arrives-at-the-pre-20160901', 'https://www2.pictures.zimbio.com/gi/Usher+2010+Keep+Child+Alive+Black+Ball+Gjqt5R-ZypOl.jpg', 'https://www.rap-up.com/app/uploads/2010/06/eminem-recovery-promo-1280x720.jpg', 'https://m.media-amazon.com/images/M/MV5BYzAyNGJmNTQtN2Y5ZS00MGE4LWEzNDYtM2RhYzM1Y2FhM2MxXkEyXkFqcGdeQXVyNzI2NTQ5MTU@._V1_SY1000_CR0,0,853,1000_AL_.jpg', 'https://thesource.com/wp-content/uploads/2018/02/drake.jpg', 'https://i.pinimg.com/originals/47/5d/b7/475db7bbb112f15679183508c38a448c.jpg', 'https://www1.pictures.zimbio.com/gi/Flo+Rida+2012+NCLR+ALMA+Awards+Show+osSWMxkj0iPl.jpg', 'https://media1.popsugar-assets.com/files/thumbor/DM9qOlm598Ppb3oxORm9Ax74-7o/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2013/08/22/703/n/1922153/104f870eed7181d6_151408073_10/i/Nicki-Minaj-2012.jpg', 'https://static.billboard.com/files/stylus/1366469-adele-qa-year-in-music-2011-617-409-compressed.jpg', 'https://cdn1.thr.com/sites/default/files/imagecache/landscape_928x523/2011/11/lamfao-publicity-2011-l.jpg', 'https://img.washingtonpost.com/rf/image_480w/2010-2019/WashingtonPost/2012/06/15/Style/Images/Photo_Maroon5_300RGB.jpg?uuid=_vqeiLb0EeGrVwBtAoUQ4g', 'https://i.pinimg.com/originals/34/5c/3c/345c3cb6e679b4fb6d0c17a1d4abc590.jpg', 'https://pbs.twimg.com/media/CGmKtfbUAAE04_1.jpg', 'https://2911.us/wp-content/uploads/2019/02/PostMalone_600pix.jpg', 'https://static.billboard.com/files/media/Cardi-B-press-photo-by-Raven-Varona-2018-billboard-1548-768x433.jpg']) 
ser = pd.Series(data, index =['Ke$ha', 'Iyaz', 'Lady Gaga', 'Owl City', 'Jay-Z', 'Alicia Keys', 'Jason Derulo', 'Jay Sean', 'Lil Wayne', 'David Guetta', 'Akon', 'Lil Jon', 'The Black Eyed Peas', 'Young Money', 'Lloyd', 'Rihanna', 'Jeezy', 'Train', 'Ludacris', 'Taylor Swift', 'Justin Bieber', 'Lady Antebellum', 'Taio Cruz', 'B.o.B', 'Bruno Mars', 'Usher', 'Eminem', 'Katy Perry', 'Drake', 'Pitbull', 'Flo Rida', 'Nicki Minaj', 'Adele', 'LMFAO', 'Maroon 5', 'Ariana Grande', 'The Weeknd', 'Post Malone', 'Cardi B'])
ser

In [ ]:
df3 = df3.insert(0, 'images', ser)
df3

In [ ]:
df3 = pd.read_csv('C:/Users/HELoz/Downloads/2010stop10hits.csv')
df3 = df3.set_index('Unnamed: 0')
df3

In [ ]:
df3.insert(0, 'images', ser)
df3

In [ ]:
#df3.to_csv('C:/Users/HELoz/Downloads/2010stop10hitsmodified.csv')